version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter:3.0.1
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
      - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
